version: "3"
services:
  redis:
    image: redis:6-alpine

  rabbitmq:
    image: rabbitmq:3.8-alpine

  worker:
    build:
      context: backend/server_web
    command: bash run_celery.sh
    environment:
      BROKER_URI: amqp://guest:guest@rabbitmq:5672
      BACKEND_URI: redis://redis:6379/0
      SERVER_MODEL_URL: server_model
    depends_on:
      - server_model
      - server_backend
      - redis
      - rabbitmq

  server_model:
    container_name: server_model
    build:
      context: backend/server_model
      dockerfile: Dockerfile
    volumes:
      - ./backend/server_web/static:/server_web_static

  web_module:
    container_name: web_module
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "21665:8080"

  server_backend:
    container_name: server_backend
    build:
      context: backend/server_web
      dockerfile: Dockerfile
    environment:
      BROKER_URI: amqp://guest:guest@rabbitmq:5672
      BACKEND_URI: redis://redis:6379/0
      DB_URL: mariadb+mariadbconnector://root:lkdawd+2dawpd20@db:3306
      USERNAME: root
      MYSQL_ROOT_PASSWORD: lkdawd+2dawpd20
      SERVER_MODEL_URL: server_model
    volumes:
      - ./server/server_web/static:/app/static
    ports:
      - "21666:3117"
    depends_on:
      - db
      - server_model

  db:
    image: mariadb:10
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: lkdawd+2dawpd20
    volumes:
      - ./backend/server_web/routers/database/data/mysql:/var/lib/mysql
