name: app-build-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to github
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'
          IMAGE_ID: ghcr.io/tapliershiru/testing:${{ github.run_id }}
          
      - name: Build docker
        run: |
          echo ---Building and starting up docker---
          docker-compose -f ./docker-compose.yml -p $IMAGE_ID up -d
          echo ---Container is up!!!---
        env:
          IMAGE_ID: ghcr.io/tapliershiru/testing:${{ github.run_id }}
        
      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
      
      - name: Push image to GitHub Container Registry
        run: |
          docker push $IMAGE_ID
        env:
          IMAGE_ID: ghcr.io/tapliershiru/testing:${{ github.run_id }}
